-- Baseline schema (fresh project, no prod data).
-- MySQL compat: VARCHAR PKs + VARCHAR(64) branch (TEXT cannot be indexed without length),
-- username VARCHAR(128) UNIQUE (same reason), no TEXT DEFAULTs.
CREATE TABLE IF NOT EXISTS projects (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_projects_branch ON projects(branch);
CREATE TABLE IF NOT EXISTS vessels (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_vessels_branch ON vessels(branch);
CREATE TABLE IF NOT EXISTS drydocks (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_drydocks_branch ON drydocks(branch);
CREATE TABLE IF NOT EXISTS dockSlots (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_dockSlots_branch ON dockSlots(branch);
CREATE TABLE IF NOT EXISTS inventory (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_inventory_branch ON inventory(branch);
CREATE TABLE IF NOT EXISTS movements (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_movements_branch ON movements(branch);
CREATE TABLE IF NOT EXISTS equipment (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_equipment_branch ON equipment(branch);
CREATE TABLE IF NOT EXISTS bookings (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_bookings_branch ON bookings(branch);
CREATE TABLE IF NOT EXISTS subcontractors (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_subcontractors_branch ON subcontractors(branch);
CREATE TABLE IF NOT EXISTS workOrders (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_workOrders_branch ON workOrders(branch);
CREATE TABLE IF NOT EXISTS termins (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_termins_branch ON termins(branch);
CREATE TABLE IF NOT EXISTS employees (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_employees_branch ON employees(branch);
CREATE TABLE IF NOT EXISTS invoices (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_invoices_branch ON invoices(branch);
CREATE TABLE IF NOT EXISTS payables (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_payables_branch ON payables(branch);
CREATE TABLE IF NOT EXISTS ncr (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_ncr_branch ON ncr(branch);
CREATE TABLE IF NOT EXISTS incidents (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_incidents_branch ON incidents(branch);
CREATE TABLE IF NOT EXISTS inspections (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_inspections_branch ON inspections(branch);
CREATE TABLE IF NOT EXISTS purchaseOrders (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_purchaseOrders_branch ON purchaseOrders(branch);
CREATE TABLE IF NOT EXISTS requisitions (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_requisitions_branch ON requisitions(branch);
CREATE TABLE IF NOT EXISTS vendors (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_vendors_branch ON vendors(branch);
CREATE TABLE IF NOT EXISTS quotations (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_quotations_branch ON quotations(branch);
CREATE TABLE IF NOT EXISTS clients (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_clients_branch ON clients(branch);
CREATE TABLE IF NOT EXISTS documents (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_documents_branch ON documents(branch);
CREATE TABLE IF NOT EXISTS surveys (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_surveys_branch ON surveys(branch);
CREATE TABLE IF NOT EXISTS activities (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_activities_branch ON activities(branch);
CREATE TABLE IF NOT EXISTS services (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_services_branch ON services(branch);
CREATE TABLE IF NOT EXISTS spareparts (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_spareparts_branch ON spareparts(branch);
CREATE TABLE IF NOT EXISTS boq (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_boq_branch ON boq(branch);
CREATE TABLE IF NOT EXISTS branches (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_branches_branch ON branches(branch);
CREATE TABLE IF NOT EXISTS attendance (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_attendance_branch ON attendance(branch);
CREATE TABLE IF NOT EXISTS payroll (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_payroll_branch ON payroll(branch);
CREATE TABLE IF NOT EXISTS taxPeriods (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_taxPeriods_branch ON taxPeriods(branch);
CREATE TABLE IF NOT EXISTS rfqs (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_rfqs_branch ON rfqs(branch);
CREATE TABLE IF NOT EXISTS changeOrders (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_changeOrders_branch ON changeOrders(branch);
CREATE TABLE IF NOT EXISTS risks (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_risks_branch ON risks(branch);
CREATE TABLE IF NOT EXISTS leaves (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_leaves_branch ON leaves(branch);
CREATE TABLE IF NOT EXISTS trainings (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_trainings_branch ON trainings(branch);
CREATE TABLE IF NOT EXISTS timesheets (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_timesheets_branch ON timesheets(branch);
CREATE TABLE IF NOT EXISTS drawings (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_drawings_branch ON drawings(branch);
CREATE TABLE IF NOT EXISTS toolbox (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_toolbox_branch ON toolbox(branch);
CREATE TABLE IF NOT EXISTS warranties (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_warranties_branch ON warranties(branch);
CREATE TABLE IF NOT EXISTS calibrations (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_calibrations_branch ON calibrations(branch);
CREATE TABLE IF NOT EXISTS communications (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_communications_branch ON communications(branch);
CREATE TABLE IF NOT EXISTS contracts (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_contracts_branch ON contracts(branch);
CREATE TABLE IF NOT EXISTS bast (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_bast_branch ON bast(branch);
CREATE TABLE IF NOT EXISTS trials (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_trials_branch ON trials(branch);
CREATE TABLE IF NOT EXISTS requests (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_requests_branch ON requests(branch);
CREATE TABLE IF NOT EXISTS clientPos (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_clientPos_branch ON clientPos(branch);
CREATE TABLE IF NOT EXISTS settings (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_settings_branch ON settings(branch);
CREATE TABLE IF NOT EXISTS coa (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_coa_branch ON coa(branch);
CREATE TABLE IF NOT EXISTS journals (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_journals_branch ON journals(branch);
CREATE TABLE IF NOT EXISTS assets (id VARCHAR(128) PRIMARY KEY, branch VARCHAR(64), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_assets_branch ON assets(branch);
CREATE TABLE IF NOT EXISTS users (id VARCHAR(128) PRIMARY KEY, username VARCHAR(128) UNIQUE, pass_hash TEXT NOT NULL, name TEXT NOT NULL, role TEXT NOT NULL, email TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS wbs_by_project (project_id VARCHAR(128) PRIMARY KEY, data TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS team_by_project (project_id VARCHAR(128) PRIMARY KEY, data TEXT NOT NULL);
